import { EventProps } from './eventTypes';

export const EVENTS_DATA: EventProps[] = [
  {
    id: '1',
    title: 'Czytanie przy winie',
    subtitle: 'Wersja online, grupa Discord',
    description: 'Zapraszamy na comiesięczną sesję wspólnego czytania przy winku (lub herbatce). Idealne na jesienny wieczór!',
    date: { day: '06', month: 'LISTOPAD', weekday: 'Czw' },
    time: '20:00 - 22:00',
    location: 'Online / Discord',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=2940&auto=format&fit=crop',
    type: 'open',
    status: 'open',
    ticketLink: 'https://lu.ma/twoj-link-1',
    themeColor: 'bg-white',
  },
  {
    id: '2',
    title: 'Łódzkie Targi Książki',
    description: 'Nie mogłybyśmy opuścić lokalnych targów, więc wybieramy się na małe książkowe zakupy.',
    date: { day: '22', month: 'LISTOPAD', weekday: 'Sb' },
    time: '11:00 - 15:00',
    location: 'Łódź Expo',
    imageUrl: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?q=80&w=2940&auto=format&fit=crop',
    type: 'members-only',
    status: 'last-places',
    ticketLink: 'https://lu.ma/twoj-link-2',
    themeColor: 'bg-white',
  },
  {
    id: '3',
    title: 'Klubowa Wigilia',
    subtitle: 'Spotkanie specjalne',
    description: 'Ostatnie spotkanie w roku. Będą pierogi, secret santa i mnóstwo dobrej zabawy.',
    date: { day: '20', month: 'GRUDZIEŃ', weekday: 'Sb' },
    time: '20:00',
    location: 'Restauracja Obiecana',
    imageUrl: 'https://images.unsplash.com/photo-1576402187878-974f70c890a5?auto=format&fit=crop&q=80&w=2835',
    type: 'members-only',
    status: 'sold-out',
    ticketLink: 'https://lu.ma/twoj-link-3',
    themeColor: 'bg-[#5e1c1c]',
  },
];